title: KORIX Learning Center
description: Articles by KORIX, originally published at korixinc.com/learning-center.
url: https://korixinc.github.io
baseurl: /korix-content
theme: minima
permalink: /:slug/
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
